apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: observability-platform
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: observability-platform
data:
  DB_HOST: "mysql-cluster"
  DB_PORT: "3306"
  DB_NAME: "notificationdb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap:9092"
