---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBihDWi5NBsmk1Qc+Gziw0AsfrIp5f/85CEeB9HNpOGd7N8vxUSFNhj/8iMRF6WdbxKMt9BYIw7+qMBoVNxLAH/7h84QQcSY70dhPZSdXwRETiryYsO2geLieJUaXFatbJ5i0bEMLZ5PDlOKy0Fsh+Z3BuY3Qhwx20HdYi3H0KECqxluFBcDXvDt/8gfeQ3Lbsx1oLHNUcsxyc5F3JHibBQWn6/WfLYTH8dAlI9GVM4Gf0tz0FdMfyEz0KCLIBM18Rq5Dl1SEThOKKk8r8TwJtQrB1qtcIp7lJgv4LPwHUrbhxnBoGFZBAxQaBfG0E/Tuwslr6sLGdkf42n6NXkSPmMcgOGx/uotUl1d8K6s959oqWsFIHBSdUDq3sgv2r1lotSUDfRnOHiSE04I3Fy21Xo6RzI44BuGxmfBaA083NCCWclGd4mOpef8ayQm2JDc28GpTKUMkBqgZuyiU/NGtjCgiglXDS9dWdiyySBK+s/vomJRpRNjoro547LCtZlCf9wzhOSmZ4+iw71wzMTKP/l+2pgfgSPf0FJCQ0Kb0QL3Xxhql0imOSxTVxofGSZHkTfJxN7eGbIvFsyVPEY202vhe7p6Kgh8ioAWghDjYW8LllZKPUJ3G1sxqVoNjr+azfmF+ODqeHEwr8daMT85i+SfUlJDB3YSGrbYXsPB5awr6TD5VwK8x6eN0WtNGeDyQ2UzJbsqLd6me8=
    admin-user: AgBmUAixSrrOd1Jqaw9/AmxQWsjBuRBWC4HXjwxwlJn03ZrjFD/+F9duQx1oeixbKhFyoNmODTocpOsiS/oLE4BmvM3AF12Zsmx1EwaTrq9BCW1YbW9Hdve7tnkqaVHMWH9o25dNZ6UrmmYn9dgcMibHF54PUIhFLWkhHPImzAqmSMzusNeFft/L6Q+D5fcmq46agkWjzByGKV7Du3mVhsh5OIJO0KOyPfysP5z8LCmSVup1HhqcyhJ8NqQUwfsTAf9Dx5GXaWeTYJLX6BbCcpKp47EK5PLJ91oOkt2CQKTud6DwU4cY3l03rQM6L6/FqInujZycc92VIZW9+DjY7FIh1ITqd9QeHmo0Bvk0hKJ80C2JndyRqSK7mmGjNrGiB0+asZJ3gxZ0zZu7DqJx8clDMNVW+oPoIdF4LCqME0t498iGS8f1La8O2Vb2qgjpoSr3YgF87l1SzQ0Q2F9oywTPyTRIWwitrcTDdekcQeAx+6cBGyRwY8ttY56NpVPmw3sIJbcGwDUfSjU7drYxAJgMJnkPAN3k7t2Rlu2zTkjo0F4KYAfyYBEGLfoa6XNod44iPqTBdaEBiC6g1clx6pQSxtN5PO0N5CI7cC5HpmITkcKt4kH3ZCXAkyDdQ12u33+RkLSalOUAn33a+2l8XcpOehFSuWFficSwextjAGAQeaC3S+KjX6ZbX93Be5xriQE678rEpQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
