---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: obs-apps
spec:
  encryptedData:
    DB_PASSWORD: AgAFXKsliP8RKLZ4CuBcHXYFmMuGpMCP1u7Z7G11TF/Ahh1E4XnXAOrFhxU2dK2Ow0b2Mm7lBPmPujbMbxBgZfozr0bG/mUR+Qnrc9Cw6hiCggODmverMwGxuWQJ2Q0EiR66SiFW+7weIRLy/9aml95RRPhO6lytwJmxozRC4AsOAM7FKuxmnF33gJfx4jZ7sseyEsXMKXE8JdtI/bXc86a487kmCs9MiZklPA7ig7wtaww9fHNBQv3z0Ob3RpVWxg3P89GQWcuz/tIINiy9kIMSjf+2YUVHluEJ1uY5b7VblXrSZyz27OZ12NnYm8ukk6Fra3GVzpPwdoAK835rnKVauVXt2JiJCUpZAKBywT/i5JPXPPmTQgc00FyThTyoZG2Rmy4AadecyTS1sa7rjoGvU6aGW7yunwtcE4dMEJ2dHFshh6LXh0qg0vSWT+2Qn1Ww9RcIFmudVbSiXUjL1YpE/BMmFjCR6xixYlT6Ih0pPn6DA5qsu6k851lAuVaiSkM8Tk/m/ZDYAR2WaODVYAA2hXFAYdIuQ6S45Yx17r9oYmS6MeEAYuRfrTAMImLLft+M2plu11xqaPakQxIMMivYWyrYD11vCh9Xz2Pbb1dMvmsJptwac+PBOOeLOv9eMnb/lTF6580t/P2//nwpJ3tlkDdBak2nK5cuQ+0V/upnDWZbtXp32Dtquy+6DcL6LUUPwsb8RbcFCxI=
    DB_USERNAME: AgCbQa+FKa3kjuMkYFL8ogBz18PkWSgy2FRHlb0qDbjNgV1jpRAbomW+At0ZCBkALLy5u3Q+7HD5UEhJrA61yZx7vuM2+F7wRoOZTZgz4izPht7JarNqrgxL/aiizq6SF4vVbvvJBSTCSWjzaEvgM7Wnon7lXbW3kpKu4RMp896pExGkhoTSBg1bW28QkeCiEGOkTG3ZmSmuQT5rZp9L4zHTm6p8FUt8pFG+OUure15hkJlZ1g/hqBqBhNdphoHNovBUWz1mxBDAJpm/AgSnzSUIco3+peYUfOZUSvBZgFQOtpsvUO/b5fdS97lDa/OTGPXjiVmy2MLrnyIObvaYcoVqATbSvk9iEnUVgvP0oU4UUxK5rQQNmbrRAKCBAm6dbRGMOy/wXq1oD+9tMGCAyoQq13PjQOFLLJRSD1h2WrYkRAR2ZHUwd1qpGDrr5N6nt601f1X3nYASZI71Mi0PZ+eaSV4kYpsNozAhrqyRoPSE74cLDR6OrQJbBOVbjBkl0HYfV0UlfqQukXtaLrHARokASFC2eQImNM29x7Ez9D7jtJ8CO6RL3KvzZlRfXkYQetzkC0De2JHuE5KFJA2TsHvYMfv8sQ6oL7svCR3PBhJlkcUSxiBQRCglPo73WXhUmD/9BkzTmjcJ7/RIZDTyhKkiHqqVxo1cNkN+aMHZ3JUMpokVjv2O7lpXNiXxYCiWUwTVZcYH
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: obs-apps
