---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-secret
  namespace: obs-apps
spec:
  encryptedData:
    DB_PASSWORD: AgAZWnP9qCJ0Ho3ILj1Uu+WqpLwozE/G5bc9N1NwP+qFqdeBNcNdmH2p19bSMOlLdB4IZSXNLv7g7Y/mH16EklBsmrgj6RHPAq2EZ25mpf+581GlZHU8Ze5yUiTPFpmf7s17uchSsOk5/sHxT43wO+9IFaDUly9hjevMMkTABavQfzX00ZA/0IaqCze4FBkmWBg6kmqIubVvSfd/iqlv2LXIGJF9izELMnLvabInk1SjtspBQUIP5oErHgPM4CqvM8zH8AdAYUPtWGqDNfJm2h48B6gk1DOHoctDS/574rHt+8APZgmQ1XMEaid3ED2pcPJebHpTgUG4PiidtyCeWP8rpddyK1wsIUYrxzmDRFKtvCReVOzIP/rViMukVZ7B+r4n1baTtiD8Z+DIsUQFdcn9R4CAO1AS2TYY3vUom3FoAvRW8CN3I+VOCIZgpjFOMohdEj9NbYVYXC8AzDjEvceFf/xa++y6qt7mYS2lfmLLcQR0FGEltwv2HfjOG5G0S5DU04H6Icr3dEEcLPr1uMLNLiLievZfTI0lq7JxGydl1nYwAPZ2tmxOB8XA216hDePR7mOaqacdEpAal1E1ABcCts7f543n2Dz8uft2vLEGjTBVKH2I/n9feRdHrmn9ZLROa0YPpfKDLB8KJusSFHOwXhAZ1qnB3fAy5Z6+j9qlnyyn9Lsd8ub79HqrDxAnFBDAXOoO+d8Y7B8=
    DB_USERNAME: AgBv3tJ0d2Mj+Ba/dCpDtJVcn5Lpu9ikFoOZHQt5dzIqiazcINaw5xYIbm7co3jwp0Eo9nsAJgJNTStVxq2t8zLOUcGq/IAQj3y82vlzt7SH8jlSjRZF6bHjZUKujviCo4VD4YBVzUNFPsPcvNNnchtaiv8fIM+hI6lAxCFUlI4cIazY2FCmi107zv2EdRCHRf89xdbe3A6yMOVaIvURyMUvJwxiDjVETbOFtAg4InjsK8pH8vWX1mzxLm31Du2K7ICYP4VolCxgK6CiwDQ9Phy1rHy+KB7XZZ7mPnFW6T5yB5FA0ayZUZseBASefJNFQADF2BU5mJhtQnr6wPeeke0YeZikFs2KLV5TxROHu1hBQ5/6TcIpytoLGHxFg8pNyH185PgRV1VdY0mLDgG4souEVLsb7GEHEJqV/lEwhUE/vrL8hEJ6BUGO160oltzv47YaEmfUmtt/vlytB95AHdiigvE9y7f1cJqIxTMh6XMjSXBkjF3L0sgVnq7Y4hSFCoFYOUi2fNeQ9q0xiiCchV2I81na4A/j4/0bNYU9K0f4Ty1o3qRWosl9LaTbl9ZieyzVKUT0JY54YIJwHrFFJMMMPct1KGwgYuim9evHuPMk8yWA9jGJSZaos6fSMSVF7E3x+8l9C7UH/89BUNMbjuYb5Fq2HMoG8KkSH6vZqr/M1Im5NkyXsCyC/NsPn6nEB+U//Q7G
  template:
    metadata:
      creationTimestamp: null
      name: order-service-secret
      namespace: obs-apps
