---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-service-secret
  namespace: obs-apps
spec:
  encryptedData:
    DB_PASSWORD: AgAFEmSRhlFiWHnUKN229HZbeWpYNDKjqNI8OUNRMNsBcd7Cysndf0Eq2a1HkG2QH8QDVudaK5gHh4FzWxmHhl/Mu3MMjNgUdUf9W1MylHi9yY+bqnkCzfF+7fCoBTfSQh9+HfGeHhV8AXYo7m94+LYcOFmLb2AKP+gkgEKF9eDUNNKxhmOLv6YPcJZEXVCqePIaOMMpyNzTE18DkVb7KtbiEsQwYvrQdUVfbaB3VCJ2/y31cQDxU+p5SJEEfLg7o2dMkAZrMDG1PoGzw1ASB9HCPbtiIsiwCXSIJezZ5K/P140V1RENyKuF7sKpGR1Sek2sGGg5O/ojTP7ZgfVVo+BW/kjU+Wtjc377PMflA1zmQepPOKlCLKyMwDD30+/JQ+PPEYnW8PN0akPoNSwJNvOvs5Jj+QhH536CzYwwzt2cxC377WPJOny9OaZnYbETpTM+VWPzozeMQzQQR6LhbbsD22kJx+b+pc/2g421O678105VtUc+KcFvTNFUJWnwWUa/zIZ1pqAjExrt2f6rnuJi5AJEXWqJHrVyZnUX+IayAk3Rayeh9FhAd34DsUAUIGGiYglSwY8DmUaadRVWTRqan6YellGZ3zZCtArQ/wnkZM0odUXp+4RIPYHmHPJt7nxLczsTvRLvLRR80MFH17U1gSgry9tje7JVn1QtGH/xDY/VaA6pN2hpwFkMegDdOCMVNa8VEoL3F1A=
    DB_USERNAME: AgBmiuft9w2HxFGIGER7hRfIlMxkitlkXXzNxZ4bgUobJHCn7dGeerL2RJ+pFYQA9eOz1YFvnAVsT1dydKriFifkSoBGa+svbMS4ZQHFPUA++MWnTNPAn/ce6rBMnMu109QdNRP59CFbOeVHHV3ZmS6j+3MkoQHD7BldrYmdkTkOCD7eoXDKjc9soQRoKU/ezWZS35a+u/IJqPrZvcMruKtzdJQbq484v77eiWOWtdX2y9ksFD8k4zFP0r7mvWvToDEBsJLFkJHVFQeCSSHfWhE+28lS5TSqRh8jIccHVRHuPfuh6c6fxq5s7Wj85nKy8REzFEWe0aBIAHGEipCbsrEoFS4ut7CysMVQuUA0zrIyOWdwyx8uWjRsYnjat4RTXwhnpTmPbxrzlXf0KrVisq19gpBqIWEE4P2cufeE4iba2ULVLencM/iJm1C9JE5GSfEkq5sWgNXdbNa3tP/EkPdzCnL6yr9YL/TJvOOEzgLZRFIXQFODI1P1k0M/Do2C8lxNmdI4Yu5viAmEMK/k3JDjy5I5gjNh8eBiPoZYFwv6dufR/9sFuD4P0Y5wsereMypn54rekEBOJz25vN0jgipGTneWP74PnKzJjEcspZ+g2iVVk+aGtSp3cg5ribCVgLy8tbYqx9AiryDbAChlo46M6MeO22cMUQ2xG6pIk2ZboDxmgUj2VL+7x5POUeFGiU+xNeqD
  template:
    metadata:
      creationTimestamp: null
      name: notification-service-secret
      namespace: obs-apps
