apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: apps
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: observability-platform
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "orderdb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  PAYMENT_SERVICE_URL: "http://payment-service"
