apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  # strimzi-operator Application이 먼저 sync된 후 적용해야 함 (Kafka CRD 의존)
  source:
    repoURL: https://github.com/jaehoon9875/observability-platform
    path: infra/manifests/kafka
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
