apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: default
  # 주의: Operator 삭제 시 관리 중인 InnoDBCluster에 영향 가능
  # mysql Application보다 먼저 sync되어야 함
  sources:
    - repoURL: https://mysql.github.io/mysql-operator/
      chart: mysql-operator
      targetRevision: 2.2.7
      helm:
        valueFiles:
          - $values/infra/helm/mysql-operator/custom-values.yaml
    - repoURL: https://github.com/jaehoon9875/observability-platform
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
